.PHONY: name

name:
	go run test/character/main.go $(char) name
physical:
	go run test/character/main.go $(char) physical
backstory:
	go run test/character/main.go $(char) backstory
weapon:
	go run test/character/main.go $(char) weapon

intro:
	go run test/story/main.go $(palyer) $(opponent) intro